import net.fabricmc.loom.task.prod.ClientProductionRunTask

plugins {
    id "fabric-loom" version "${loom_version}"
    id "com.diffplug.spotless" version "8.1.0"
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

version = project.mod_version
group = project.maven_group

def ENV = System.getenv()

def mcUsername =
        System.getenv("MQTTBOT_USERNAME")
                ?: project.findProperty("bot_username")
                ?: "Player999"

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    flatDir { dirs 'libs' }

//    ivy {
//        url = "https://github.com/cabaletta/baritone/releases/download"
//        patternLayout {
//            artifact("v[revision]/[module]-[revision].jar")
//        }
//        metadataSources {
//            artifact() // no ivy.xml or pom
//        }
//    }
    maven {
        name = 'babbaj-repo'
        url = 'https://babbaj.github.io/maven/'
    }
    maven {
        name = 'tolland-wurst'
        url = uri("https://maven.pkg.github.com/tolland/Wurst7")
        credentials {
            username = System.getenv("GITHUB_ACTOR")
            password = System.getenv("GITHUB_TOKEN")
        }
    }
//    ivy {
//        url 'https://github.com/tolland/Wurst7/releases/download'
//        patternLayout {
//            artifact '[revision]/[module]-[revision](-[classifier]).[ext]'
//        }
//        metadataSources {
//            artifact()
//        }
//    }
}


dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.8:2025.09.14@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
    implementation 'org.yaml:snakeyaml:2.0'
    modImplementation "cabaletta:baritone-api-fabric:${baritone_version}"
    modImplementation "net.wurstclient:wurst-client:1.21.8-develop"
    modApi("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_api_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    implementation "dev.babbaj:nether-pathfinder:${project.nether_pathfinder_version}"
    implementation "io.moquette:moquette-broker:0.17"

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"

    testImplementation "org.mockito:mockito-core:${project.mockito_version}"
// optional for JUnit 5 integration if you plan to use MockitoExtension
//    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"

}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "mqttbot-test"
        enableGameTests = false
        enableClientGameTests = true
        eula = true
        username = "Mqtt-Bot"
    }
}

sourceSets {
////    client {
////        compileClasspath += main.compileClasspath
////        runtimeClasspath += main.runtimeClasspath
////    }
//    gametest {
//        compileClasspath += sourceSets.main.compileClasspath
////        compileClasspath += sourceSets.client.compileClasspath
////
////        runtimeClasspath += sourceSets.main.runtimeClasspath
////        runtimeClasspath += sourceSets.client.runtimeClasspath
//    }
//    "src-py" {
//        java {
//            srcDir "src-py"
//        }
//    }
}

compileJava.dependsOn spotlessApply

afterEvaluate {
    sourceSets {
//        gametest {
//            compileClasspath += sourceSets.main.compileClasspath
//
//            runtimeClasspath += sourceSets.main.runtimeClasspath
//        }
        "src-py" {
            java {
                srcDir "src-py"
            }
        }
    }

}
loom {

    accessWidenerPath = file("src/main/resources/mqttbot.accesswidener")

//    splitEnvironmentSourceSets()

    mods {
        "mqttbot" {
            sourceSet sourceSets.main
        }
    }
    runs {
        client {
            programArgs(
                    "--username", mcUsername as String,
//                    "--quickPlaySingleplayer", "TestFabricModWorld1"
                    "--quickPlayMultiplayer", "docker.lan:25565"
            )
        }
        clientGameTest {
            source sourceSets.gametest
        }
    }
}


processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    // Minecraft 1.21 uses Java 21.
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
    from {
        configurations.compileClasspath.findAll {
            (it.name.endsWith('jar') && it.name.contains('org.eclipse.paho.client.mqttv3'))
        }
    }.collect {
        zipTree(it)
    }
}

spotless {
    java {
        removeUnusedImports()
        leadingSpacesToTabs()
        trimTrailingWhitespace()
        eclipse().configFile(file("codestyle/formatter.xml"))
    }
    json {
        target("src/**/*.json", "src/**/*.mcmeta")
        gson().indentWithSpaces(2).version("2.11.0")
    }
}

test {
    useJUnitPlatform()
}


tasks.register("runProductionClientGameTest", ClientProductionRunTask) {
    jvmArgs.add("-Dfabric.client.gametest")
    // Whether to use XVFB to run the game, using a virtual framebuffer. This is useful for headless CI environments.
    // Defaults to true only on Linux and when the "CI" environment variable is set.
    // XVFB must be installed, on Debian-based systems you can install it with: `apt install xvfb`
    useXVFB = true
}

tasks.register("printGametestClasspath") {
    doLast {
        sourceSets.gametest.compileClasspath.each {
            println it
        }
    }
}


tasks.register("printMainClientClasspath") {
    doLast {
        sourceSets.main.compileClasspath.each {
            println it
        }
    }
}
